// utils/api.js
// Utility functions to interact with Google Gemini API (Free Tier)

export async function getApiKey() {
  return new Promise((resolve) => {
    chrome.storage.local.get(['geminiApiKey'], (result) => {
      resolve(result.geminiApiKey || null);
    });
  });
}

export async function callLLM(systemInstruction, userPrompt) {
  const apiKey = await getApiKey();
  if (!apiKey) {
    throw new Error("API Key not found. Please set your free Gemini API key in the extension settings.");
  }

  // 1. Fetch available models dynamically to completely bypass "not found" errors
  const modelsRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`);
  const modelsData = await modelsRes.json();
  
  if (!modelsRes.ok) {
    throw new Error(modelsData.error?.message || "Failed to list models for this API key.");
  }

  if (!modelsData.models || modelsData.models.length === 0) {
    throw new Error("Your API key has no models available.");
  }

  // Find the best available Gemini model
  let selectedModelName = "";
  const validModels = modelsData.models.filter(m => 
    m.supportedGenerationMethods && m.supportedGenerationMethods.includes("generateContent")
  );
  
  const flashModel = validModels.find(m => m.name.includes("gemini-1.5-flash"));
  const proModel = validModels.find(m => m.name.includes("gemini-1.5-pro"));
  
  if (flashModel) selectedModelName = flashModel.name;
  else if (proModel) selectedModelName = proModel.name;
  else if (validModels.length > 0) selectedModelName = validModels[0].name;
  else throw new Error("No compatible models found for this API key.");

  // selectedModelName comes back as "models/gemini-1.5-flash", so we put it directly in the URL
  const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/${selectedModelName}:generateContent?key=${apiKey}`;
  
  const response = await fetch(GEMINI_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      contents: [
        {
          role: "user",
          parts: [{ text: `System Instructions: ${systemInstruction}\n\nUser Input: ${userPrompt}` }]
        }
      ],
      generationConfig: {
        temperature: 0.7
      }
    })
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error?.message || `HTTP Error ${response.status}`);
  }

  const data = await response.json();
  if (!data.candidates || data.candidates.length === 0) {
    throw new Error("No response generated by the AI.");
  }
  
  return data.candidates[0].content.parts[0].text;
}

// Prompt functions
export const explainPrompt = (text, mode) => {
  let instruction = "Explain the following text clearly and concisely.";
  if (mode === "simple") instruction = "Explain the following text in very simple terms, avoiding jargon.";
  if (mode === "eli5") instruction = "Explain the following text as if I am 5 years old. Use an analogy if helpful.";
  if (mode === "bullets") instruction = "Summarize the following text using 3-5 key bullet points.";
  
  return {
    system: "You are a highly intelligent and helpful AI research assistant.",
    user: `${instruction}\n\nText: "${text}"`
  };
};

export const summarizePrompt = (content) => {
  return {
    system: "You are an expert reading comprehension AI and content summarizer.",
    user: `Please thoroughly analyze and summarize the following webpage content. 
Structure your response exactly like this:
**Short Summary**: A 2-3 sentence overview.
**Key Takeaways**:
- Point 1
- Point 2
- Point 3
**Insights**: One or two interesting observations or implications from the text.

Content: ${content.substring(0, 15000)}` 
  };
};

export const qaPrompt = (context, question) => {
  return {
    system: "You are a strict AI assistant reading a specific document. Answer ONLY using the provided context. If the context does not contain the answer, say 'I cannot find the answer to this question in the page content.' Do not use outside knowledge.",
    user: `Context:\n${context.substring(0, 15000)}\n\nQuestion: ${question}`
  };
};
